baseURL = 'https://moonhack.1stkingslangleyscouts.com.au/'
languageCode = 'en-us'
title = 'Moonhack 2025'
theme = 'hyde'

[params]
description = " "
author = "1st Kings Langley Scouts"
themeColor = "theme-base-0d"
layoutReverse = true

[Menus]
main = [
    { Name = "1st Kings Langley Scouts", URL = "https://1stkingslangleyscouts.com.au" },
    { Name = "Moonhack 2025", URL = "https://moonhack.com" },
]

[caches]
[caches.images]
dir = ':cacheDir/images'
